comp_snibble.o: comp_snibble.c dact.h config.h comp_fail.h comp_snibble.h \
  buffer.h sort.h
comp_delta.o: comp_delta.c dact.h config.h comp_fail.h comp_delta.h \
  buffer.h
comp_text.o: comp_text.c dact.h config.h comp_fail.h comp_text.h buffer.h
comp_rle.o: comp_rle.c dact.h config.h comp_fail.h comp_rle.h
cipher_chaos.o: cipher_chaos.c dact.h config.h comp_fail.h ui.h \
  cipher_chaos.h
cipher_sub.o: cipher_sub.c cipher_sub.h dact.h config.h comp_fail.h \
  parse.h ui.h
cipher_psub.o: cipher_psub.c dact.h config.h comp_fail.h cipher_psub.h \
  parse.h ui.h
comp_lzoox.o: comp_lzoox.c dact.h config.h comp_fail.h comp_lzoox.h
comp_lzooy.o: comp_lzooy.c dact.h config.h comp_fail.h comp_lzooy.h
comp_lzota.o: comp_lzota.c dact.h config.h comp_fail.h comp_lzota.h
comp_bzlib.o: comp_bzlib.c dact.h config.h comp_fail.h comp_bzlib.h
comp_zlib.o: comp_zlib.c dact.h config.h comp_fail.h comp_zlib.h
comp_mzlib.o: comp_mzlib.c dact.h config.h comp_fail.h comp_mzlib.h
comp_mzlib2.o: comp_mzlib2.c dact.h config.h comp_fail.h comp_mzlib2.h
dact_common.o: dact_common.c dact.h config.h comp_fail.h parse.h \
  dendian.h crc.h math.h dact_common.h algorithms.h comp_plain.h \
  comp_rle.h comp_delta.h comp_zlib.h comp_mzlib.h comp_mzlib2.h \
  comp_bzlib.h comp_snibble.h comp_text.h comp_lzoox.h comp_lzooy.h \
  comp_lzota.h ciphers.h cipher_chaos.h cipher_sub.h cipher_serpent.h \
  cipher_psub.h module.h header.h net.h ui.h
comp_fail.o: comp_fail.c dact.h config.h comp_fail.h
comp_plain.o: comp_plain.c dact.h config.h comp_fail.h comp_plain.h
buffer.o: buffer.c dact.h config.h comp_fail.h buffer.h
header.o: header.c dact.h config.h comp_fail.h header.h
sort.o: sort.c dact.h config.h comp_fail.h sort.h
dact.o: dact.c dact.h config.h comp_fail.h parse.h dendian.h crc.h math.h \
  dact_common.h algorithms.h comp_plain.h comp_rle.h comp_delta.h \
  comp_zlib.h comp_mzlib.h comp_mzlib2.h comp_bzlib.h comp_snibble.h \
  comp_text.h comp_lzoox.h comp_lzooy.h comp_lzota.h ciphers.h \
  cipher_chaos.h cipher_sub.h cipher_serpent.h cipher_psub.h module.h \
  header.h net.h ui.h
module.o: module.c dact.h config.h comp_fail.h module.h algorithms.h \
  comp_plain.h comp_rle.h comp_delta.h comp_zlib.h comp_mzlib.h \
  comp_mzlib2.h comp_bzlib.h comp_snibble.h comp_text.h comp_lzoox.h \
  comp_lzooy.h comp_lzota.h ciphers.h cipher_chaos.h cipher_sub.h \
  cipher_serpent.h cipher_psub.h parse.h net.h ui.h
parse.o: parse.c dact.h config.h comp_fail.h buffer.h parse.h crc.h ui.h
dendian.o: dendian.c dact.h config.h comp_fail.h dendian.h
crc.o: crc.c dact.h config.h comp_fail.h crc.h
net.o: net.c dact.h config.h comp_fail.h net.h parse.h crc.h
ui.o: ui.c dact.h config.h comp_fail.h ui.h
dact.o: dact.c dact.h config.h comp_fail.h parse.h dendian.h crc.h math.h \
  dact_common.h algorithms.h comp_plain.h comp_rle.h comp_delta.h \
  comp_zlib.h comp_mzlib.h comp_mzlib2.h comp_bzlib.h comp_snibble.h \
  comp_text.h comp_lzoox.h comp_lzooy.h comp_lzota.h ciphers.h \
  cipher_chaos.h cipher_sub.h cipher_serpent.h cipher_psub.h module.h \
  header.h net.h ui.h
comp_snibble.so: comp_snibble.c dact.h config.h comp_fail.h comp_snibble.h \
  buffer.h sort.h
comp_delta.so: comp_delta.c dact.h config.h comp_fail.h comp_delta.h \
  buffer.h
comp_text.so: comp_text.c dact.h config.h comp_fail.h comp_text.h buffer.h
comp_rle.so: comp_rle.c dact.h config.h comp_fail.h comp_rle.h
cipher_chaos.so: cipher_chaos.c dact.h config.h comp_fail.h ui.h \
  cipher_chaos.h
cipher_sub.so: cipher_sub.c cipher_sub.h dact.h config.h comp_fail.h \
  parse.h ui.h
cipher_psub.so: cipher_psub.c dact.h config.h comp_fail.h cipher_psub.h \
  parse.h ui.h
comp_lzoox.so: comp_lzoox.c dact.h config.h comp_fail.h comp_lzoox.h
comp_lzooy.so: comp_lzooy.c dact.h config.h comp_fail.h comp_lzooy.h
comp_lzota.so: comp_lzota.c dact.h config.h comp_fail.h comp_lzota.h
comp_bzlib.so: comp_bzlib.c dact.h config.h comp_fail.h comp_bzlib.h
comp_zlib.so: comp_zlib.c dact.h config.h comp_fail.h comp_zlib.h
comp_mzlib.so: comp_mzlib.c dact.h config.h comp_fail.h comp_mzlib.h
comp_mzlib2.so: comp_mzlib2.c dact.h config.h comp_fail.h comp_mzlib2.h
dact_common.so: dact_common.c dact.h config.h comp_fail.h parse.h \
  dendian.h crc.h math.h dact_common.h algorithms.h comp_plain.h \
  comp_rle.h comp_delta.h comp_zlib.h comp_mzlib.h comp_mzlib2.h \
  comp_bzlib.h comp_snibble.h comp_text.h comp_lzoox.h comp_lzooy.h \
  comp_lzota.h ciphers.h cipher_chaos.h cipher_sub.h cipher_serpent.h \
  cipher_psub.h module.h header.h net.h ui.h
comp_fail.so: comp_fail.c dact.h config.h comp_fail.h
comp_plain.so: comp_plain.c dact.h config.h comp_fail.h comp_plain.h
buffer.so: buffer.c dact.h config.h comp_fail.h buffer.h
header.so: header.c dact.h config.h comp_fail.h header.h
sort.so: sort.c dact.h config.h comp_fail.h sort.h
dact.so: dact.c dact.h config.h comp_fail.h parse.h dendian.h crc.h math.h \
  dact_common.h algorithms.h comp_plain.h comp_rle.h comp_delta.h \
  comp_zlib.h comp_mzlib.h comp_mzlib2.h comp_bzlib.h comp_snibble.h \
  comp_text.h comp_lzoox.h comp_lzooy.h comp_lzota.h ciphers.h \
  cipher_chaos.h cipher_sub.h cipher_serpent.h cipher_psub.h module.h \
  header.h net.h ui.h
module.so: module.c dact.h config.h comp_fail.h module.h algorithms.h \
  comp_plain.h comp_rle.h comp_delta.h comp_zlib.h comp_mzlib.h \
  comp_mzlib2.h comp_bzlib.h comp_snibble.h comp_text.h comp_lzoox.h \
  comp_lzooy.h comp_lzota.h ciphers.h cipher_chaos.h cipher_sub.h \
  cipher_serpent.h cipher_psub.h parse.h net.h ui.h
parse.so: parse.c dact.h config.h comp_fail.h buffer.h parse.h crc.h ui.h
dendian.so: dendian.c dact.h config.h comp_fail.h dendian.h
crc.so: crc.c dact.h config.h comp_fail.h crc.h
net.so: net.c dact.h config.h comp_fail.h net.h parse.h crc.h
ui.so: ui.c dact.h config.h comp_fail.h ui.h
dact.so: dact.c dact.h config.h comp_fail.h parse.h dendian.h crc.h math.h \
  dact_common.h algorithms.h comp_plain.h comp_rle.h comp_delta.h \
  comp_zlib.h comp_mzlib.h comp_mzlib2.h comp_bzlib.h comp_snibble.h \
  comp_text.h comp_lzoox.h comp_lzooy.h comp_lzota.h ciphers.h \
  cipher_chaos.h cipher_sub.h cipher_serpent.h cipher_psub.h module.h \
  header.h net.h ui.h
